baseURL: "https://rustamlatypov.github.io"
title: Rustam Latypov
theme: PaperMod

enableInlineShortcodes: true
enableRobotsTXT: true
pagination:
  pagerSize: 20

taxonomies:
    tag: tags

menu:
    main:
      - name: About
        url: about/
        weight: 1
      - name: Papers
        url: papers/
        weight: 2
      - name: Puzzles
        url: puzzles/
        weight: 3

params:
    description: "This website hosts Moritz-Maria von Igelfeld's research papers, books, course materials, data, curriculum vitae, and contact information."
    author: Rustam Latypov
    # googleAnalyticsID: G-XXXXX
    DateFormat: January 2006
    defaultTheme: light
    hideFooter: true
    disableThemeToggle: true
    ShowShareButtons: false
    ShowReadingTime: false
    disableSpecial1stPost: true
    disableAnchoredHeadings: true
    ShowPostNavLinks: false
    ShowBreadCrumbs: false
    ShowCodeCopyButtons: true
    ShowAllPagesInArchive: false
    MainSections: [about,papers,puzzles]
    ShowToc: false
    disableScrollToTop: true
    TocOpen: true
    ShowWordCount: false
    UseHugoToc: true
    comments: false
    math: true
    profileMode:
          enabled: true
          title: Rustam Latypov
          subtitle: "I'm a postdoc in the group of Jara Uitto at Aalto University with research and teaching experience in algorithm design and combinatorics. My research interests lie in the mathematical foundations of distributed and parallel computing. I specialize in fundamental graph problems in modern models of computing. During my free time I climb rocks."
          imageUrl: prof_pic.jpg
          imageWidth: 200
          imageHeight: 200
          buttons:
            - name: About
              url: about/
            - name: Papers
              url: papers/
            - name: Puzzles
              url: puzzles/


    socialIcons:
        - name: Email
          url: mailto:rustam.latypov@aalto.fi
        - name: Location
          url: location/
        - name: Google Scholar
          url: https://scholar.google.com/citations?user=dh5n3p4AAAAJ&hl=en
        - name: GitHub
          url: https://github.com/rustamlatypov
        - name: CV
          url: cv.pdf

    assets:
        disableScrollBarStyle: true
    cover:
        hiddenInList: false
        hiddenInSingle: true
    label:
      text: Rustam Latypov
      icon: favicon.ico
      iconHeight: 18

markup:
    goldmark:
        renderer:
            unsafe: true
    highlight:
        guessSyntax: true
        style: autumn
    tableOfContents:
        endLevel: 2
        ordered: false
        startLevel: 2
